version: "3.6"
services:
    gitlab:
        image: "gitlab/gitlab-ce:latest"
        network_mode: "host"
        hostname: "localhost"
        environment:
            GITLAB_OMNIBUS_CONFIG: |
                external_url 'http://localhost:8929'
                gitlab_rails['gitlab_shell_ssh_port'] = 2224
            # - "8929:8929"
            # - "2224:22"
        # ports:
        volumes:
            - "./gitlab/config:/etc/gitlab"
            - "./gitlab/logs:/var/log/gitlab"
            - "./gitlab/data:/var/opt/gitlab"
        shm_size: "256m"
    antaeus:
        network_mode: "host"
        build:
            context: ./
            dockerfile: Dockerfile
        env_file:
            - .env
