version: "3.6"
services:
    gitlab:
        image: "gitlab/gitlab-ce:latest"
        network_mode: "host"
        hostname: "gitlab.example.com"
        environment:
            GITLAB_OMNIBUS_CONFIG: |
                external_url 'http://gitlab.example.com:8929'
                gitlab_rails['gitlab_shell_ssh_port'] = 2224
            # - "8929:8929"
            # - "2224:22"
        # ports:
        volumes:
            - "./gitlab/config:/etc/gitlab"
            - "./gitlab/logs:/var/log/gitlab"
            - "./gitlab/data:/var/opt/gitlab"
        shm_size: "256m"
